name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x' # Adjust to the specific version used by the team
        channel: 'stable'

    - name: Install Dependencies
      run: flutter pub get

    - name: Check Formatting
      run: dart format --set-exit-if-changed .

    - name: Analyze Code
      run: flutter analyze

    - name: Run Tests
      run: flutter test
